version: "3.8"
services:
  server:
    image: somukandula/integrate1
    restart: always
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
